/**
 * jsonl.ts — all knowledge of Claude Code's (undocumented, evolving) transcript format
 * lives here. Everything else operates on the typed helpers below, so a format change
 * is a one-file patch.
 *
 * Format facts verified against real transcripts (see plan):
 *  - A transcript is JSON-Lines; each line is one Entry. Many `type`s exist; only
 *    `user`/`assistant` entries carry a `.message`. Use an allowlist, never a denylist.
 *  - Message entries form a tree via parentUuid; file order is chronological for them,
 *    but the tree BRANCHES on edits/retries. The active thread = walk parentUuid back
 *    from the latest leaf, then reverse.
 *  - The true project path is the `cwd` field (the dash-encoded dir name is ambiguous).
 *  - `ai-title` is regenerated many times; the last one is the current title.
 *  - tool_results arrive as role:"user" entries whose content is a list with tool_result
 *    blocks — they are NOT human messages.
 */
import { readFileSync } from "node:fs";

export interface Block {
  type?: string;
  text?: string;
  thinking?: string;
  name?: string; // tool_use
  input?: Record<string, unknown>; // tool_use
  id?: string; // tool_use
  tool_use_id?: string; // tool_result
  content?: unknown; // tool_result
}

export interface Message {
  role?: string;
  content?: string | Block[];
}

export interface Entry {
  type?: string;
  uuid?: string;
  parentUuid?: string | null;
  timestamp?: string;
  isSidechain?: boolean;
  isMeta?: boolean;
  cwd?: string;
  sessionId?: string;
  gitBranch?: string;
  message?: Message;
  aiTitle?: string;
  [k: string]: unknown;
}

/** Read a .jsonl transcript, tolerating malformed lines (skip, don't throw). */
export function readEntries(file: string): Entry[] {
  const raw = readFileSync(file, "utf8");
  const out: Entry[] = [];
  for (const line of raw.split("\n")) {
    const s = line.trim();
    if (!s) continue;
    try {
      out.push(JSON.parse(s) as Entry);
    } catch {
      /* skip malformed line */
    }
  }
  return out;
}

export function isMessageEntry(e: Entry): boolean {
  return (
    (e.type === "user" || e.type === "assistant") &&
    e.message != null &&
    typeof e.uuid === "string"
  );
}

/** True project path. Prefer the cwd field over the (ambiguous) directory name. */
export function getCwd(entries: Entry[]): string | undefined {
  for (const e of entries) {
    if (typeof e.cwd === "string" && e.cwd) return e.cwd;
  }
  return undefined;
}

export function getGitBranch(entries: Entry[]): string | undefined {
  for (const e of entries) {
    if (typeof e.gitBranch === "string" && e.gitBranch) return e.gitBranch;
  }
  return undefined;
}

/** Current title = the LAST ai-title entry (titles are regenerated repeatedly). */
export function getTitle(entries: Entry[]): string | undefined {
  let title: string | undefined;
  for (const e of entries) {
    if (e.type === "ai-title" && typeof e.aiTitle === "string" && e.aiTitle.trim()) {
      title = e.aiTitle.trim();
    }
  }
  return title;
}

/** Wrapped strings that look like user text but are slash-command / hook plumbing. */
const COMMAND_WRAPPER_TAGS = [
  "command-name",
  "command-message",
  "command-args",
  "local-command-stdout",
  "local-command-stderr",
  "bash-input",
  "bash-stdout",
  "bash-stderr",
  "user-prompt-submit-hook",
];

function startsWithWrapper(s: string): string | undefined {
  const t = s.trimStart();
  for (const tag of COMMAND_WRAPPER_TAGS) {
    if (t.startsWith(`<${tag}>`)) return tag;
  }
  return undefined;
}

/**
 * Harness-injected user-role messages that are NOT real human input: background-task
 * notifications, Conductor/system instructions, file-attachment context, system reminders,
 * and post-compaction continuation summaries. They have string content (so they'd otherwise
 * look human) and pollute turn counts and output. Match on leading marker after trim.
 */
const SYSTEM_INJECTION_PREFIXES = [
  "<task-notification>",
  "<system_instruction>",
  "<system-reminder>",
  "<local-command-caveat>",
  "[SYSTEM NOTIFICATION",
  "This session is being continued from a previous conversation",
  "Caveat: The messages below were generated by the user while running",
];

function isSystemInjected(s: string): boolean {
  const t = s.trimStart();
  return SYSTEM_INJECTION_PREFIXES.some((p) => t.startsWith(p));
}

/** Remove harness noise blocks the harness sometimes appends to real human messages. */
function sanitizeHumanText(s: string): string {
  return s
    .replace(/<system-reminder>[\s\S]*?<\/system-reminder>/g, "")
    .replace(/<system_instruction>[\s\S]*?<\/system_instruction>/g, "")
    .trim();
}

export type UserKind = "human" | "command" | "system" | "tool_result" | "meta" | "other";

export interface UserClass {
  kind: UserKind;
  text: string;
  commandName?: string;
}

/** Classify a role:"user" entry: real human input vs tool-result vs command plumbing. */
export function classifyUser(entry: Entry): UserClass {
  const content = entry.message?.content;
  if (entry.isMeta) return { kind: "meta", text: "" };

  if (typeof content === "string") {
    const wrapper = startsWithWrapper(content);
    if (wrapper) {
      const m = content.match(/<command-name>\s*([^<]+?)\s*<\/command-name>/);
      return { kind: "command", text: content, commandName: m?.[1]?.trim() };
    }
    if (isSystemInjected(content)) return { kind: "system", text: "" };
    const clean = sanitizeHumanText(content);
    return clean ? { kind: "human", text: clean } : { kind: "system", text: "" };
  }

  if (Array.isArray(content)) {
    if (content.some((b) => b?.type === "tool_result")) {
      return { kind: "tool_result", text: "" };
    }
    // Rare: user content as text blocks (e.g. attachments). Join any text.
    const text = content
      .filter((b) => b?.type === "text" && typeof b.text === "string")
      .map((b) => b.text as string)
      .join("\n")
      .trim();
    return text ? { kind: "human", text } : { kind: "other", text: "" };
  }

  return { kind: "other", text: "" };
}

export interface ToolUse {
  name: string;
  input?: Record<string, unknown>;
}

export interface AssistantParts {
  text: string;
  thinking: string;
  toolUses: ToolUse[];
}

export function getAssistantParts(entry: Entry): AssistantParts {
  const content = entry.message?.content;
  const parts: AssistantParts = { text: "", thinking: "", toolUses: [] };
  if (typeof content === "string") {
    parts.text = content;
    return parts;
  }
  if (!Array.isArray(content)) return parts;
  const texts: string[] = [];
  const thinks: string[] = [];
  for (const b of content) {
    if (b?.type === "text" && typeof b.text === "string") texts.push(b.text);
    else if (b?.type === "thinking" && typeof b.thinking === "string") thinks.push(b.thinking);
    else if (b?.type === "tool_use" && typeof b.name === "string") {
      parts.toolUses.push({ name: b.name, input: b.input });
    }
  }
  parts.text = texts.join("\n").trim();
  parts.thinking = thinks.join("\n").trim();
  return parts;
}

/**
 * Reconstruct the ACTIVE conversation thread (excluding abandoned/edited-out branches):
 * take the latest message entry as the tip, walk parentUuid back to the root, reverse.
 * Falls back to plain file order if the chain looks broken (covers <50% of messages).
 */
export function reconstructActiveThread(entries: Entry[]): Entry[] {
  const msgs = entries.filter(isMessageEntry);
  if (msgs.length === 0) return [];

  const byUuid = new Map<string, Entry>();
  for (const e of msgs) byUuid.set(e.uuid as string, e);

  const chain: Entry[] = [];
  const seen = new Set<string>();
  let cur: Entry | undefined = msgs[msgs.length - 1]; // latest leaf (file order is chronological)
  while (cur && cur.uuid && !seen.has(cur.uuid)) {
    seen.add(cur.uuid);
    chain.push(cur);
    const p: string | null | undefined = cur.parentUuid;
    cur = typeof p === "string" ? byUuid.get(p) : undefined;
  }
  chain.reverse();

  if (chain.length < msgs.length * 0.5) return msgs; // broken graph → safe fallback
  return chain;
}

/** First real human message (skips command wrappers / meta / tool-results). */
export function firstHumanMessage(entries: Entry[]): string | undefined {
  for (const e of entries) {
    if (e.type !== "user" || !isMessageEntry(e)) continue;
    const c = classifyUser(e);
    if (c.kind === "human" && c.text.trim()) return c.text.trim();
  }
  return undefined;
}

/** Count real human turns (the "size" of a session). */
export function countHumanTurns(entries: Entry[]): number {
  let n = 0;
  for (const e of entries) {
    if (e.type !== "user" || !isMessageEntry(e)) continue;
    if (classifyUser(e).kind === "human") n++;
  }
  return n;
}
